add solution for 1-module 1-task
js-tasks-ru/nodejs-20211109_dmitriy-fadeev2 pull request #1
Opened 2021-11-12 10:10 UTC by DmFadeev

2021-11-12 10:10 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @tadjik1 должен запустить тесты.

2021-11-12 10:12 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-11-12 10:17 UTC, tadjik1 requested changes
@DmFadeev верните, пожалуйста, задачи удаленные. я понимаю, из-за них тесты не проходят - но это нестрашно, я все равно смогу принять решение задачи суммы чисел.

2021-11-14 10:16 UTC, tadjik1 commented
@DmFadeev напишите, пожалуйста,если вам нужна помощь с тем, чтобы файлы вернуть

2021-11-17 09:09 UTC, DmFadeev commented
Здравствуйте,да,возникли проблемы с тем,чтобы вернуть файлы в директорию,не
могли бы описать инструкцию по восстановлению файлов?

вс, 14 нояб. 2021 г. в 13:16, Sergey Zelenov ***@***.***>:

> @DmFadeev <https://github.com/DmFadeev> напишите, пожалуйста,если вам
> нужна помощь с тем, чтобы файлы вернуть
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/nodejs-20211109_dmitriy-fadeev2/pull/1#issuecomment-968262272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAONW7YS3JYZV474V42VSTUL6D63ANCNFSM5H4PFDWQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-17 09:25 UTC, DmFadeev commented
В общем,я не придумал ничего лучше для работой с этим
гитом,дитей сатаны,как скопировать зип файл с репозитория и вручную
переместить недостающие файлы в нужную директорию

ср, 17 нояб. 2021 г. в 12:08, дмитрий фадеев ***@***.***>:

> Здравствуйте,да,возникли проблемы с тем,чтобы вернуть файлы в
> директорию,не могли бы описать инструкцию по восстановлению файлов?
>
> вс, 14 нояб. 2021 г. в 13:16, Sergey Zelenov ***@***.***>:
>
>> @DmFadeev <https://github.com/DmFadeev> напишите, пожалуйста,если вам
>> нужна помощь с тем, чтобы файлы вернуть
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/js-tasks-ru/nodejs-20211109_dmitriy-fadeev2/pull/1#issuecomment-968262272>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANAONW7YS3JYZV474V42VSTUL6D63ANCNFSM5H4PFDWQ>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-11-17 13:54 UTC, tadjik1 commented
я бы наверное также сделал, давайте помогу. просто не смог раньше, сейчас сделаю

2021-11-18 10:00 UTC, tadjik1 approved these changes
👍

2021-11-18 10:00 UTC, merged